### ISSUE TITLE
Failing tests since 0.116

### ISSUE THREAD

**Issue by pjfl** [rjbs/Test-Deep#30]
Getting smoke test failures since 0.116 was released

t/13functions.t .... ok
Prototype mismatch: sub main::blessed ($) vs none at t/15io.t line 12.
    
    #   Failed test 'Delete tmp files'
    #   at t/15io.t line 369.
    #          got: 'Test::Deep::Blessed=HASH(0x8053d4378)'
    #     expected: 'File::DataClass::IO'
    
    #   Failed test 'Delete tmp files - non default template'
    #   at t/15io.t line 371.
    #          got: 'Test::Deep::Blessed=HASH(0x8053c5540)'
    #     expected: 'File::DataClass::IO'
    # Looks like you failed 2 tests of 3.

These test were passing at 0.115
9d945b68-1842-11e5-a64c-d58bc1bbb74a

**Comment by rjbs** [comment]
You don't indicate *what* is getting smoke failures, so I really can't do much.

That said, please try with 0.117, released moments ago.  Maybe the fixed bug is related.

If that does not help, please re-open this ticket with more context so I can try to reproduce the problem.
