### ISSUE TITLE
Incorrect examples in documentation

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Test-Deep#32]
In the [documentation](https://metacpan.org/pod/Test::Deep#Without-Test::Deep) example looks rendered incorrectly:

    Say you want to test a function which returns a string. You know
    that your string should be a 7 digit number beginning with 0, eq
    is no good in this situation, you need a regular expression. So
    you could use Test::More's like() function:
    
        like($string, '/^0d{6}$/', "number looks good");
        #                ^^^ Should be \d here

It looks like backslash is missed before `d`. This occurs in this example and few more examples below in the doc.

BTW, wouldn't it better to use regexps, not strings in examples?

        like($string, qr/^0\d{6}$/, "number looks good");

**Comment by simbabque** [comment]
There is another typo/copy&paste issue, in https://metacpan.org/pod/Test::Deep#noclass-thing:

> This can be useful when you want to check that objects have been constructed correctly but you don't want to write lots of blesses. If `@people` is an array of Person objects then
> 
> ```
> cmp_deeply(\@people, noclass([
>   bless {name => 'John', phone => '555-5555'}, "Person",
>   bless {name => 'Anne', phone => '444-4444'}, "Person",
> ]));
> ```

In the _before_ example the `noclass()` should not be there.

**Comment by rjbs** [comment]
Thanks!  Applied all of this.
