### ISSUE TITLE
Support nested hash in superhashof and subhashof

### ISSUE THREAD

**Issue by zhengwy888** [rjbs/Test-Deep#35]
Thanks for the great library!
I am curious if it's worth adding support in the superhashof and subhash method. Without this superhash/subhash comparison stops after first level keys.
These are the tests that I wrote, but after trying to fiddle around with the code I couldn't get both the original test 'superhash ok' and this new 'nested superhash ok' to pass.

``` perl

    check_test(
        sub {
            cmp_deeply({key1 => "a", key2 => { key3 => "a", key4 => "b" }}, superhashof({key1 => "a", key2 => { key3 => "a"}}),
                "nested superhash ok");
        },
        {
            name => "nested superhash ok",
            actual_ok => 1,
            diag => "",
        }
    );

    check_test(
        sub {
            cmp_deeply({key1 => "a", key2 => { key3 => "a"}}, subhashof({key1 => "a", key2 => { key3 => "a", key4 => "b" }}),
                "nested subhash ok");
        },
        {
            name => "nested subhash ok",
            actual_ok => 1,
            diag => "",
        }
    );
```

Would you please consider adding this featuer?
Thank you!

**Comment by karenetheridge** [comment]
Isn't that just:

    cmp_deeply(
        {
            key1 => "a",
            key2 => { key3 => "a", key4 => "b" }
        },
        superhashof({
            key1 => "a",
            key2 => superhashof({ key3 => "a" })
        }),
        "nested superhash ok",
    );

Data is matched from the inner layers up (as you can see from the code, there
is a recursive descent into the data structures) - only as inner layers
continue to match does the stack unwind and outer layers are compared.

**Comment by zhengwy888** [comment]
Yeah that does work. I am looking for a function that takes a hash and converts all the hash in the child level into a superhashof object. The level of nesting may not be known ahead of time. 
of course I can iterate over all the keys in the expected hash recursively and convert all hash into superhashof(), but a convenience method would be nice.

**Comment by rjbs** [comment]
This should be pretty easy to implement, but I don't see myself doing it.  I'd maybe accept a patch, but you'd also be able to just release to CPAN.  For now, closing this issue.  Thanks for your interest!
