### ISSUE TITLE
all() should not clobber $@

### ISSUE THREAD

**Issue by FGasper** [rjbs/Test-Deep#36]
Following up on issue #26, the clobbering of $@ in all() is unexpected and is better avoided.

While I’ll admit that I’m unusually attentive to $! (and $?, and $^E) for a Perl hacker :), I think there’s more general consensus that `eval {}` should not clobber $@ beyond its own scope.

**Comment by FGasper** [comment]
Incidentally, the $@ clobber appears to have been a recent addition … it’s making lots of IO::Die’s tests fail.

**Comment by FGasper** [comment]
I am, of course, aware of the idea of never assuming that another piece of code won’t violently futz with globals that my code cares about. Still, FWIW, IMO testing code like Test::Deep should take extra care not to futz with its environment.

**Comment by rjbs** [comment]
Got a test case?

**Comment by FGasper** [comment]
`perl -MTest::Deep -e'$@ = 123; all(123); print $@'`

**Comment by FGasper** [comment]
Ah, sorry … you mean an actual test … I’ll add it and resubmit.
