### ISSUE TITLE
Fails to declare test prereqs with old EUMM

### ISSUE THREAD

**Issue by cpansprout** [rjbs/Test-Deep#40]
Quoth Makefile.PL:

```
  ( $ExtUtils::MakeMaker::VERSION < 6.63_03 ? 'BUILD_REQUIRES' : 'TEST_REQUIRES' ) => {
    'Test::More'       => '0.88',
    'Test::Tester'     => $tt_prereq,
  },
```

BUILD_REQUIRES was added in 6.55_01.  If the version of EUMM is less than that (any default installation of 5.10.0 or lower with no EUMM upgrade), then Test::Tester fails to get declared as a prerequisite.

**Comment by karenetheridge** [comment]
Test::Deep still isn't packaged with Dist::Zilla, which generates a Makefile.PL that handles falling back from TEST_REQUIRES to BUILD_REQUIRES to PREREQ_PM.

**Comment by dur-randir** [comment]
>Test::Deep still isn't packaged with Dist::Zilla

While this could pass as an argument if this module has never worked on older perls, it had. So, I can't understand your argument, when you've broken it with the commit 61dd5fa5040964054b03f28652cd79d3d46e9916 when you could've not.

**Comment by rjbs** [comment]
I've pushed 67cef75, which may fix this.  I'll ask for some more eyes before I release.
