### ISSUE TITLE
wishlist: true and false

### ISSUE THREAD

**Issue by torbjorn** [rjbs/Test-Deep#41]
I found myself first spending some time hunting down bugs in a nested test structure where I had

```
... ,
foo => 0,
```

instead of 

```
... ,
foo => bool(0),
```

(since my real code returned undef and not zeros)

which again lead me to think hey why not have functions for true and false, it would make the code prettier and never ever give this same bug again, ie:

```
...,
foo => false, # or true
```

its way clearer and arguably less error prone and its easier to type (on latin1 languaged keyboards at least)

**Comment by rjbs** [comment]
Added, today, in trial release. You must request them explicitly.
