### ISSUE TITLE
wishlist: unique() and same()

### ISSUE THREAD

**Issue by rjbs** [rjbs/Test-Deep#46]
From work Slack:

idea for the future, what do you think:

make a Test::Deep check like:  my $uniques = unique; my $same = same;

then you can put $uniques into a structure somewhere; every time cmp_Deeply hits one of them, it says "if the value at this point is the same as any other point, error; otherwise, okay"

opposite for $same

like ignore() except must match other occurances

and you could (of course?) re-use between cmp_deeply calls

**Comment by karenetheridge** [comment]
Interesting idea, but I'd do it in a separate distribution.

There are other Test::Deep::* plugins in the ecosystem -- we need more!

**Comment by rjbs** [comment]
Afterward, you can inspect `$uniques` for its values.  Better still, I imagine:

```perl
my $unique = unique;
cmp_deeply(
  $have,
  { username => $unique->('username'), manager => $unique->('manager') }
);

like($unique->('manager')->value, qr/z/i, "only people with Zs are managers");
```

This ensures that `username` and `manager` are distinct values in the structure, and it saves them for later re-use.  This also implies a third test should exist, `save`, which just saves values without caring if they're the same or different.

There are two possible places to store state:  in the thing returned by `unique()`, or in the Test::Deep stack.  If the former, you must be careful to always have a fresh state before testing if that's what you want.  I think that's probably doable.  In this case, `$unique` is encapsulating state.  So, further, we don't want `unique` and `save` tests directly, but:

```perl
my $global = correlator(); # this name is probably not the best

for my $have (@results) {
  my $local = correlator();
  cmp_deeply(
    $have,
    { id => $global->unique('id'), scores => array_each($local->save('score')) },
  );

  my @scores = $local->values('score');
  diag "scores: @scores";
}
```

**Comment by rjbs** [comment]
I'm happy to put this in another dist, I'm just putting my thoughts here for now.

**Comment by rjbs** [comment]
I've begun implementing at https://github.com/rjbs/Test-Deep-Collect
