### ISSUE TITLE
Using NoTest and then Test::Deep in tests causes $Test to not initalise to Test::Builder

### ISSUE THREAD

**Issue by Relequestual** [rjbs/Test-Deep#53]
As noted previous in 2008 at: https://rt.cpan.org/Public/Bug/Display.html?id=32330

> When I build a test that does "use Test::Deep" and then accesses cmp_deeply and friends, I get this error message: "Can't call method "ok" on an undefined value at /usr/share/perl5/Test/Deep.pm line 113." The reason is that while Test:Deep:NoTest avoids pulling in test::builder, it enforces this for subsequent Test::Deep imports as well, thus breaking Test::Deep.

After discussing my discovery of this issue with @shadowcat-mst on perl irc, he suggested a fix, which worked. I'll submit a PR shortly.

**Comment by akarelas** [comment]
I came across this issue myself, and it's a bit important for my app.
How come this issue & bugfix has been stalled for so many years?

**Comment by rjbs** [comment]
Fixed by #76 (?)
