### ISSUE TITLE
Can default export behavior be removed?

### ISSUE THREAD

**Issue by zbentley** [rjbs/Test-Deep#58]
If I do:

`perl -MList::AllUtils=:all -MScalar::Util=blessed -MTest::Deep -e ''`

I get:

```
Prototype mismatch: sub main::blessed ($) vs none at -e line 0.
Prototype mismatch: sub main::all (&@) vs none at -e line 0.
Prototype mismatch: sub main::any (&@) vs none at -e line 0.
Prototype mismatch: sub main::none (&@) vs none at -e line 0.
```

This is consistent with the documented behavior in the `EXPORTS` section of the perldoc. 

However, given how common the List::Util functions and the use of blessed etc. are in both test and non-test code, would it be possible to revisit the decision of `Test::Deep` to export (nearly) everything by default? The names are so common as to be virtually guaranteed to collide in a lot of code.

I think having an `:all` (or `:v0`,`:v1`, etc) export tag would really improve interoperability with other code.

However, this would break backwards compatibility.

What are the maintainers thoughts?

**Comment by rjbs** [comment]
`use Test::Deep ':v1'` already imports everything but `Isa` and `blessed`, to help avoid this conflict.  The all/any/none one is, in my experience, much rarer.

Breaking backward compatibility of Test::Deep, though, is pretty much off the table for something like this.  It's far too high up the chain of common dependencies.  I'm happy to look at adding better-controlled tags for imports without conflicts, but not to removing things currently exported.

**Comment by zbentley** [comment]
Fair enough, thanks for the info!

**Comment by akarelas-pt** [comment]
I do: `use Test::Deep '!all', '!any';` or `use Test::Deep ':v0', '!all', '!any';` when I want to avoid the conflict with List::Util.
