### ISSUE TITLE
Add obj_by_methods comparison comparison function

### ISSUE THREAD

**Issue by robrwo** [rjbs/Test-Deep#77]
It would be nice to have a "obj_by_methods" comparison, that checks if two things are the same object by comparing the value of object methods (defaulting to "id").

This is really useful where you pass a row id from a database to something, and want to verify that the two row objects from DBIC are the same row.

So
```perl
cmp_deeply $got, { foo => obj_by_methods($expected) };
```
would pass if
- `$got->{foo`} has the same reference as expected (e.g. "shallow"); or
- `$got->{foo}->id` is the same as `$expected->id`

There should also be an option to pass a list of methods to compare, e.g.
```perl
obj_by_methods($expected, qw/ foo_id bar_id /);
```

**Comment by karenetheridge** [comment]
you can do this now with:

`cmp_deeply($got, methods(id => $expected_id, other_method => $expected_val, ...));`

**Comment by robrwo** [comment]
@karenetheridge Thanks, I missed that from the docs.
