### ISSUE TITLE
listmethods() works different to documentation for scalar values

### ISSUE THREAD

**Issue by dboehmer** [rjbs/Test-Deep#79]
I'm having trouble using `listmethods()` to test an object which has a method return a scalar and another method returning a list.

[Documentation](https://metacpan.org/pod/Test::Deep#listmethods) says:

> ```
>   cmp_deeply(
>     $obj,
>     listmethods(
>       name => "John",
>       ["favourites", "food"] => ["Mapo tofu", "Gongbao chicken"]
>     )
>   );
> ```
> 
> is the equivalent of checking that
> 
> ```
>   $obj->name eq "John"
>   cmp_deeply([$obj->favourites("food")], ["Mapo tofu", "Gongbao chicken"]);
> ```

But providing a scalar hash value doesn't work at all because the return value(s) from the tested method are packed into an arrayref.

```
$ perl -MTest::Deep -MDateTime -e 'cmp_deeply( DateTime->now => listmethods(year => 2020) )'
not ok 1
#   Failed test at -e line 1.
# Compared [$data->year]
#    got : ARRAY(0x559d5ae7a5a0)
# expect : '2020'
```

The test file https://github.com/rjbs/Test-Deep/blob/0eed0ef5dd204900a3da134acb1dc669c221f065/t/listmethods.t doesn't include any call with a scalar hash value.

Possible resolutions:

1. adjust the documentation to the code
2. implement the documented feature&mdash;my understanding is that currently this method can't be used with scalar hash values at all because the test will always fail→should be safe to add

I'd volunteer to provide the code fix (2) as a PR if this solution is agreed on.

**Comment by rjbs** [comment]
Thanks for the report.  I have adjusted the documentation.  I didn't want to change the long-established behavior.

**Comment by dboehmer** [comment]
Done in fa1e3cf4b0e466f00a039033c7e346c7291ec21d
