### ISSUE TITLE
Test::Deep::HashElements does not sort hash keys when checking hashes

### ISSUE THREAD

**Issue by skington** [rjbs/Test-Deep#83]
Test::Deep::HashElements->descend [goes through keys in a hash using Perl's now-random key order](https://github.com/rjbs/Test-Deep/blob/7bd9ae2696f770651799005454b9d5ad241114de/lib/Test/Deep/HashElements.pm#L29-L39), so which key it encounters first in a data structure (and therefore the error reported) will change between runs of a test. This can suggest (wrongly) that the failure encountered is varying between test runs, which is not true; what's varying is the *description* of the failure.

Consider the following toy test script:

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use Test::Deep;
use Test::More;

cmp_deeply(
    { id => 1, nickname => 'Baby',   realname => 'Emma' },
    { id => 2, nickname => 'Ginger', realname => 'Geri' }
);
done_testing();
```

This fails as e.g.
```
not ok 1
#   Failed test at /tmp/compare-hash.pl line 9.
# Compared $data->{"id"}
#    got : '1'
# expect : '2'
1..1
# Looks like you failed 1 test of 1.
```

But not consistently:
```
Theseus:~ sam$ for num in `seq 1 10`; do perl /tmp/compare-hash.pl 2>&1 | grep Compared; done 
# Compared $data->{"nickname"}
# Compared $data->{"id"}
# Compared $data->{"nickname"}
# Compared $data->{"nickname"}
# Compared $data->{"realname"}
# Compared $data->{"realname"}
# Compared $data->{"realname"}
# Compared $data->{"id"}
# Compared $data->{"realname"}
# Compared $data->{"id"}
```

In Test::Deep::HashElements and possibly elsewhere, code that iterates through `keys %$master` (or any hash), where it could return early and/or add to the stack based on the key, should iterate through `sort keys %$master` instead.

**Comment by karenetheridge** [comment]
> This can suggest (wrongly) that the failure encountered is varying between test runs, which is not true; what's varying is the description of the failure.

I'm not convinced this is a bug. If there is more than one error, they are *all* errors; you just may get a different one first each time.

**Comment by skington** [comment]
I'm currently working through a test that, I think, is behaving inconsistently from run to run; I can't be sure, because hash key randomisation means that tests that fail in the same way are reported as different failures.

You're right that in this case, it doesn't particularly matter what the error is. All I'm suggesting is: let's have the *message* always be the same, rather than introducing variability.

**Comment by rjbs** [comment]
I agree: not a bug.  On the other hand, getting the same error on the same failure feels like it would make me less crazed while debugging, so I have made the code do this.
