### ISSUE TITLE
What does this message mean?

### ISSUE THREAD

**Issue by nigelhorne** [rjbs/Test-Deep#84]
From time to time I get this message, and I can't work out what it means.  Please help - I'm sure I've done something wrong but I don't know what it is:

Found a special comparison in $data
Error: You can only use specials in the expects structure at /opt/hostedtoolcache/perl/5.34.0/x64/lib/site_perl/5.34.0/Test/Deep.pm line 360

**Comment by karenetheridge** [comment]
As per the code on that line -- you passed a Test::Deep::Cmp object as the first argument of cmp_deeply.

**Comment by nigelhorne** [comment]
I’ve given it an array (that may be empty) of Geo::Location::Point objects.

**Comment by karenetheridge** [comment]
an array, or an arrayref? if it's an empty array, then your 'expects' argument will be the first one, and will be interpreted as the $got, not the $expects.

**Comment by nigelhorne** [comment]
Hmmm. Actually that does make sense to me. I sense a refactor coming along,
even if only for GitHub actions which is the only place I get the error
message.
